### ISSUE TITLE
does not find .gitattributes 

### ISSUE THREAD

**Issue by nwabdou85** [monti-apm/meteor-agent-binary-deps#1]
I try to deploy meteor app but it throw me this error; when I inspect the patch I didn't find .gitattributes  but only profiler.node.d

`Invalid path for filesystem 'D:/home/site/repository/programs/server/npm/node_modules/meteor/montiapm_agent-binary-deps/node_modules/v8-profiler/build/Release/.deps/tmp/mt-1qb8e7n.aehs/npm/node_modules/.temp-1mz6eut.xdbmf/node_modules/v8-profiler/build/profiler/v5.7.0/node-v57-linux-x64/.gitattributes': The data area passed to a system call is too small.\r\n`

```
remote: Deployment failed
remote: Error - Changes committed to remote repository but deployment to website failed.
```

@zodern 
How can I fix it please ?

**Comment by zodern** [comment]
It looks like temp files were never removed after building the binary dependencies. Could you please try removing and adding the package again? `meteor remove montiapm:profiler` and `meteor add montiapm:profiler`.

**Comment by nwabdou85** [comment]
@zodern  there are no improvement after removing and adding montiapm:profiler; still the same error;

**Comment by zodern** [comment]
@nwabdou85 I just published version 2 which uses a different profiler. Could you please try again?
