### ISSUE TITLE
[meteor-agent-binary-deps@1.6.0]Node-gyp throw errors when upgrading meteor from 1.8.1 to 1.8.2

### ISSUE THREAD

**Issue by bavuongco10** [monti-apm/meteor-agent-binary-deps#2]
![image](https://user-images.githubusercontent.com/8337363/69881449-a9072680-12ff-11ea-911d-dc73ad1738f1.png)

It seems that someone else has a similar issue.
https://github.com/meteor/meteor/issues/10778

**Comment by zodern** [comment]
Related to https://github.com/monti-apm/meteor-profiler/issues/1

**Comment by bavuongco10** [comment]
Hello @zodern , do we have a plan to fix this, meteor 1.9 with node 12 is already out there, and we still can not upgrade because of this bug

**Comment by zodern** [comment]
I am working on it today.

**Comment by zodern** [comment]
Version 1.5.0 of `montiapm:profiler` supports Meteor 1.9.
